version: '3.7'
services:
  localghost-php:
    build: ./docker/dev/php
    container_name: localghost-php
    volumes:
      - ./:/var/www/html

  localghost-nginx:
    build: ./docker/dev/nginx
    container_name: localghost-nginx
    depends_on:
      - localghost-php
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf

  localghost-postgres:
    image: postgres:latest
    container_name: localghost-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: