api_user_register:
    path: api/users
    controller: App\Controller\UserController::registerUser
    methods: POST

api_user_remove:
    path: api/users/{id}
    controller: App\Controller\UserController::removeUser
    methods: DELETE

api_user_detail:
    path: api/users/{id}
    controller: App\Controller\UserController::detailUser
    methods: GET

api_user_list:
    path: api/users
    controller: App\Controller\UserController::listUsers
    methods: GET

api_login:
    path: api/login