# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
api_test:
    path: /test
    controller: App\Controller\TestController::test
    methods: GET
user:
    path: /users
    controller: App\Controller\UserController::index
    methods: POST
